---
# sets up mah shit

- hosts: all
  vars:
    applications:
      - google-chrome
      - firefox
      - postgres
      - spectacle
      - spotify
      - slack
      - iterm2
      - dropbox
      - steam
      - omnifocus
      - evernote
      - virtualbox
      - vagrant

  tasks:
   - name: Install libs with Homebrew
     homebrew: name={{ item }} state=present
     with_items:
       - wget
       - tmux
       - reattach-to-user-namespace # tmux config requires this
       - git
       - bash-completion
       - mysql
       - postgres
       - node
       - ctags
       - nginx
       - python3
       - leiningen
       - rust
       - the_silver_searcher
       - vim
       - weechat

   - name: Check for installed casks/apps
     shell: brew cask list | grep {{ item }}
     register: installed_applications
     with_items: applications
     ignore_errors: true

   - name: Install apps with brew-cask
     shell: brew cask install {{ item }}
     with_items: applications
     when: item not in installed_applications.results|map(attribute='stdout')

   - name: Clone dotfiles
     git: repo=git@github.com:UnicodeSnowman/dotfiles.git dest=~/.dotfiles

   - name: Clone vimfiles
     git: repo=git@github.com:UnicodeSnowman/cap-vim.git dest=~/.vim

   - name: Set up dotifles
     shell: ~/.dotfiles/setup.sh

   - name: Set up vimfiles
     shell: ~/.vim/setup.sh

   - name: Clean up brew detritus
     shell: ./clean.sh
