---
# sets up mah shit

- hosts: localhost
  vars:
    install_cask_apps: false
    applications:
      - dropbox
      - firefox
      - google-chrome
      - iterm2-beta # for Fira Code ligature support
      - font-fira-code
      - omnifocus
      - postgres
      - slack
      - spectacle
      - spotify

  tasks:
   - name: Install libs with Homebrew
     homebrew: name={{ item }} state=present
     with_items:
       - bash-completion
       - git
       - golang
       - leiningen
       - neovim/neovim/neovim
       - nginx
       - node
       - postgres
       - python3
       - reattach-to-user-namespace # tmux config requires this
       - the_silver_searcher
       - tmux
       - vim
       - wget

   - name: Check for installed casks/apps
     shell: brew cask list | grep {{ item }}
     register: installed_applications
     with_items: "{{ applications }}"
     ignore_errors: true
     when: install_cask_apps

   - name: Install apps with brew-cask
     shell: brew cask install {{ item }}
     with_items: "{{ applications }}"
     when: install_cask_apps and item not in installed_applications.results|map(attribute='stdout')

   - name: Clone dotfiles
     git: repo=git@github.com:UnicodeSnowman/dotfiles.git dest=~/.dotfiles
     tags: dotfiles

   - name: Clone vimfiles
     git: repo=git@github.com:UnicodeSnowman/cap-vim.git dest=~/.vim
     tags: vim

   - name: Set up dotfiles
     shell: ~/.dotfiles/setup.sh
     tags: dotfiles

   - name: Set up vimfiles
     shell: ~/.vim/setup.sh
     tags: vim

   - name: Clean up brew detritus
     shell: ./clean.sh
