---
# sets up mah shit

# TODO 
# - source-code-pro font
# - ssh keys?

- hosts: all
  vars:
    applications:
      - google-chrome
      - postgres
      - spectacle
      - spotify
      - slack
      - iterm2
      - dropbox
      - 1password
      - steam
      - omnifocus

  tasks:
   - name: Install libs with Homebrew
     homebrew: name={{ item }} state=present
     with_items:
       - wget
       - vim
       - tmux
       - reattach-to-user-namespace # tmux config requires this
       - git
       - bash-completion
       - mysql
       - postgres
       - node

   - name: Check for installed casks/apps
     shell: brew cask list | grep {{ item }}
     register: installed_applications
     with_items: applications
     ignore_errors: true

   - name: Install apps with brew-cask
     shell: brew cask install {{ item }}
     with_items: applications
     when: item not in installed_applications.results|map(attribute='stdout')
